services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user_admin
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_DB=orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d 
    networks:
      - integra_hub_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672" # Requisito 5.3 (Management UI)
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin_pass
    networks:
      - integra_hub_net

  orders-api:
    build: ./orders-api
    container_name: orders_api
    depends_on:
      - db
      - rabbitmq
    environment:
      - DB_HOST=db
      - DB_USER=user_admin
      - DB_PASSWORD=secret_password
      - DB_NAME=orders_db
      - RABBIT_HOST=rabbitmq
      - JWT_SECRET=mi_clave_secreta 
    ports:
      - "9000:9000"
    networks: 
      - integra_hub_net

  order-worker:
    build: ./order-worker
    container_name: order_worker
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_HOST=rabbitmq
      - DB_HOST=db
    networks:
      - integra_hub_net
    volumes:
      - ./order-worker/inbox:/app/inbox # Requisito 3.3 (Inbox)

  demo_portal:
    image: nginx:alpine
    container_name: demo_portal
    volumes:
      - ./orders-api/public:/usr/share/nginx/html 
    ports:
      - "80:80"
    depends_on:
      - orders-api  
    networks:
      - integra_hub_net

networks:
  integra_hub_net:
    driver: bridge

volumes:
  postgres_data: